jaesay/jaesay/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('portfolio.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

jaesay/portfolio/urls.py
from django.conf.urls import url
from . import views

app_name = 'portfolio'

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^SexyDashboard/$', views.sexyDashboard, name='sexyDashboard'),
    url(r'^CatCareIoTSystem/$', views.cat, name='cat'),
    url(r'^HarryCane/$', views.cane, name='cane'),
    url(r'^WeatherBot/$', views.weather, name='weather'),
    url(r'^Maze/$', views.maze, name='maze'),
]

jaesay/portfolio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

jaesay/portfolio/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def sexyDashboard(request):
    return render(request, 'sexyDashboard.html')

def cat(request):
    return render(request, 'cat.html')

def cane(request):
    return render(request, 'cane.html')

def weather(request):
    return render(request, 'weather.html')

def maze(request):
    return render(request, 'maze.html')

jaesay/portfolio/templates/cane.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">

	<head>
		<meta charset="utf-8"/>
		<title>Jaesay Portfolio</title>

		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="stylesheet" media="all" href='{% static "css/style.css" %}'/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->

		<!-- JS -->
		<script src='{% static "js/jquery-1.7.1.min.js" %}'></script>
		<script src='{% static "js/custom.js" %}'></script>
		<script src='{% static "js/tabs.js" %}'></script>
		<script src='{% static "js/css3-mediaqueries.js" %}'></script>
		<script src='{% static "js/jquery.columnizer.min.js" %}'></script>

		<!-- Isotope -->
		<script src='{% static "js/jquery.isotope.min.js" %}'></script>

		<!-- Lof slider -->
		<script src='{% static "js/jquery.easing.js" %}'></script>
		<script src='{% static "js/lof-slider.js" %}'></script>
		<link rel="stylesheet" href='{% static "css/lof-slider.css" %}' media="all"  />
		<!-- ENDS slider -->

		<!-- Tweet -->
		<link rel="stylesheet" href='{% static "css/jquery.tweet.css" %}' media="all"  />
		<script src='{% static "js/tweet/jquery.tweet.js" %}'></script>
		<!-- ENDS Tweet -->

		<!-- superfish -->
		<link rel="stylesheet" media="screen" href='{% static "css/superfish.css" %}' />
		<script  src='{% static "js/superfish-1.4.8/js/hoverIntent.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/superfish.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/supersubs.js" %}'></script>
		<!-- ENDS superfish -->

		<!-- prettyPhoto -->
		<script  src='{% static "js/prettyPhoto/js/jquery.prettyPhoto.js" %}'></script>
		<link rel="stylesheet" href='{% static "js/prettyPhoto/css/prettyPhoto.css" %}'  media="screen" />
		<!-- ENDS prettyPhoto -->

		<!-- poshytip -->
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-twitter/tip-twitter.css" %}'  />
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css" %}'  />
		<script  src='{% static "js/poshytip-1.1/src/jquery.poshytip.min.js" %}'></script>
		<!-- ENDS poshytip -->

		<!-- JCarousel -->
		<script type="text/javascript" src='{% static "js/jquery.jcarousel.min.js" %}'></script>
		<link rel="stylesheet" media="screen" href='{% static "css/carousel.css" %}' />
		<!-- ENDS JCarousel -->

		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>

		<!-- modernizr -->
		<script src='{% static "js/modernizr.js" %}'></script>

		<!-- SKIN -->
		<link rel="stylesheet" media="all" href='{% static "css/skin.css" %}'/>

		<!-- Less framework -->
		<link rel="stylesheet" media="all" href='{% static "css/lessframework.css" %}'/>

		<!-- jplayer -->
		<link href="player-skin/jplayer-black-and-yellow.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src='{% static "js/jquery.jplayer.min.js" %}'></script>

		<!-- flexslider -->
		<link rel="stylesheet" href='{% static "css/flexslider.css" %}'>
		<script src='{% static "js/jquery.flexslider.js" %}'></script>
        
                <style type="text/css">
<!--
A:link   { text-decoration: none; }
A:visited   { text-decoration: none; }
A:active   { text-decoration: none; }
A:hover   { text-decoration: none; color: #ff0000; }
//-->
</style>  
		
		
	</head>
	
	
	<body>
	
		<!-- HEADER -->
		<header>
			<div class="wrapper cf">
				
				<div id="logo">
					<a href="{% url 'portfolio:home' %}"><img  src='{% static "img/logo2.png" %}' alt="Simpler"></a>
				</div>

			</div>
		</header>
		<!-- ENDS HEADER -->
		
		<!-- MAIN -->
		<div id="main">
			<div class="wrapper cf">
    	
				
				
				
				<ul id="sub-manu">
					<li><a style="color:#000" class="selected" href="{% url 'portfolio:home' %}">MENU</a></li>
				</ul>
				
			<!-- portfolio content-->
        	<div id="portfolio-content" class="cf">        	
				
				
				
				
				<!-- project pager -->
				<div class="project-pager cf">
					<a class="previous-project" href="{% url 'portfolio:sexyDashboard' %}">&#8592; Previous project</a>
					<a class="next-project" href="{% url 'portfolio:cat' %}">Next project &#8594;</a>
				</div>
				<!-- ENDS project pager -->
					
					
					<!-- project box -->
				<div class="cheil">
                 <img src='{% static "img/dummies/slides/clearter app/all_1.jpg" %}'>
                 <video style="width:100%;" controls src='{% static "img/dummies/slides/CaneDemo.mp4" %}'>
                         Your user agent does not support the HTML5 Video element.
                 </video>
                </div>
	        		
		    	<!-- ENDS project box -->
					
					
				
									
				
    		</div>
    		<!-- ENDS portfolio content-->
			
			
			
			</div><!-- ENDS WRAPPER -->
		</div>
		<!-- ENDS MAIN -->
		
		
		<!-- FOOTER -->
		<footer>
			My Portfilio
		</footer>
		<!-- ENDS FOOTER -->
		
	</body>
	
	
	
</html>

jaesay/portfolio/templates/cat.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">

	<head>
		<meta charset="utf-8"/>
		<title>Jaesay Portfolio</title>

		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="stylesheet" media="all" href='{% static "css/style.css" %}'/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->

		<!-- JS -->
		<script src='{% static "js/jquery-1.7.1.min.js" %}'></script>
		<script src='{% static "js/custom.js" %}'></script>
		<script src='{% static "js/tabs.js" %}'></script>
		<script src='{% static "js/css3-mediaqueries.js" %}'></script>
		<script src='{% static "js/jquery.columnizer.min.js" %}'></script>

		<!-- Isotope -->
		<script src='{% static "js/jquery.isotope.min.js" %}'></script>

		<!-- Lof slider -->
		<script src='{% static "js/jquery.easing.js" %}'></script>
		<script src='{% static "js/lof-slider.js" %}'></script>
		<link rel="stylesheet" href='{% static "css/lof-slider.css" %}' media="all"  />
		<!-- ENDS slider -->

		<!-- Tweet -->
		<link rel="stylesheet" href='{% static "css/jquery.tweet.css" %}' media="all"  />
		<script src='{% static "js/tweet/jquery.tweet.js" %}'></script>
		<!-- ENDS Tweet -->

		<!-- superfish -->
		<link rel="stylesheet" media="screen" href='{% static "css/superfish.css" %}' />
		<script  src='{% static "js/superfish-1.4.8/js/hoverIntent.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/superfish.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/supersubs.js" %}'></script>
		<!-- ENDS superfish -->

		<!-- prettyPhoto -->
		<script  src='{% static "js/prettyPhoto/js/jquery.prettyPhoto.js" %}'></script>
		<link rel="stylesheet" href='{% static "js/prettyPhoto/css/prettyPhoto.css" %}'  media="screen" />
		<!-- ENDS prettyPhoto -->

		<!-- poshytip -->
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-twitter/tip-twitter.css" %}'  />
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css" %}'  />
		<script  src='{% static "js/poshytip-1.1/src/jquery.poshytip.min.js" %}'></script>
		<!-- ENDS poshytip -->

		<!-- JCarousel -->
		<script type="text/javascript" src='{% static "js/jquery.jcarousel.min.js" %}'></script>
		<link rel="stylesheet" media="screen" href='{% static "css/carousel.css" %}' />
		<!-- ENDS JCarousel -->

		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>

		<!-- modernizr -->
		<script src='{% static "js/modernizr.js" %}'></script>

		<!-- SKIN -->
		<link rel="stylesheet" media="all" href='{% static "css/skin.css" %}'/>

		<!-- Less framework -->
		<link rel="stylesheet" media="all" href='{% static "css/lessframework.css" %}'/>

		<!-- jplayer -->
		<link href="player-skin/jplayer-black-and-yellow.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src='{% static "js/jquery.jplayer.min.js" %}'></script>

		<!-- flexslider -->
		<link rel="stylesheet" href='{% static "css/flexslider.css" %}'>
		<script src='{% static "js/jquery.flexslider.js" %}'></script>
        
                <style type="text/css">
<!--
A:link   { text-decoration: none; }
A:visited   { text-decoration: none; }
A:active   { text-decoration: none; }
A:hover   { text-decoration: none; color: #ff0000; }
//-->
</style>  
		
		
	</head>
	
	
	<body>
	
		<!-- HEADER -->
		<header>
			<div class="wrapper cf">
				
				<div id="logo">
					<a href="{% url 'portfolio:home' %}"><img  src='{% static "img/logo2.png" %}' alt="Simpler"></a>
				</div>

			</div>
		</header>
		<!-- ENDS HEADER -->
		
		<!-- MAIN -->
		<div id="main">
			<div class="wrapper cf">
    	
				
				
				
				<ul id="sub-manu">
					<li><a style="color:#000" class="selected" href="{% url 'portfolio:home' %}">MENU</a></li>
				</ul>
				
			<!-- portfolio content-->
        	<div id="portfolio-content" class="cf">        	
				
				
				
				
				<!-- project pager -->
				<div class="project-pager cf">
					<a class="previous-project" href="{% url 'portfolio:cane' %}">&#8592; Previous project</a>
					<a class="next-project" href="{% url 'portfolio:maze' %}">Next project &#8594;</a>
				</div>
				<!-- ENDS project pager -->
					
					
					<!-- project box -->
				<div class="cheil">
                 <img src='{% static "img/dummies/slides/clearter app/all.jpg" %}'>
                 <video style="width:100%;" controls src='{% static "img/dummies/slides/CatDemo.mp4" %}'>
                         Your user agent does not support the HTML5 Video element.
                 </video>
                </div>
	        		
		    	<!-- ENDS project box -->
					
					
				
									
				
    		</div>
    		<!-- ENDS portfolio content-->
			
			
			
			</div><!-- ENDS WRAPPER -->
		</div>
		<!-- ENDS MAIN -->
		
		
		<!-- FOOTER -->
		<footer>
			My Portfilio
		</footer>
		<!-- ENDS FOOTER -->
		
	</body>
	
	
	
</html>

jaesay/portfolio/templates/index.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">

	<head>
		<meta charset="utf-8"/>
		<title>Jaesay Portfolio</title>
		
		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="stylesheet" media="all" href='{% static "css/style.css" %}'/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->		
				
		<!-- JS -->
		<script src='{% static "js/jquery-1.7.1.min.js" %}'></script>
		<script src='{% static "js/custom.js" %}'></script>
		<script src='{% static "js/tabs.js" %}'></script>
		<script src='{% static "js/css3-mediaqueries.js" %}'></script>
		<script src='{% static "js/jquery.columnizer.min.js" %}'></script>
		
		<!-- Isotope -->
		<script src='{% static "js/jquery.isotope.min.js" %}'></script>
		
		<!-- Lof slider -->
		<script src='{% static "js/jquery.easing.js" %}'></script>
		<script src='{% static "js/lof-slider.js" %}'></script>
		<link rel="stylesheet" href='{% static "css/lof-slider.css" %}' media="all"  />
		<!-- ENDS slider -->
		
		<!-- Tweet -->
		<link rel="stylesheet" href='{% static "css/jquery.tweet.css" %}' media="all"  />
		<script src='{% static "js/tweet/jquery.tweet.js" %}'></script>
		<!-- ENDS Tweet -->
		
		<!-- superfish -->
		<link rel="stylesheet" media="screen" href='{% static "css/superfish.css" %}' />
		<script  src='{% static "js/superfish-1.4.8/js/hoverIntent.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/superfish.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/supersubs.js" %}'></script>
		<!-- ENDS superfish -->
		
		<!-- prettyPhoto -->
		<script  src='{% static "js/prettyPhoto/js/jquery.prettyPhoto.js" %}'></script>
		<link rel="stylesheet" href='{% static "js/prettyPhoto/css/prettyPhoto.css" %}'  media="screen" />
		<!-- ENDS prettyPhoto -->
		
		<!-- poshytip -->
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-twitter/tip-twitter.css" %}'  />
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css" %}'  />
		<script  src='{% static "js/poshytip-1.1/src/jquery.poshytip.min.js" %}'></script>
		<!-- ENDS poshytip -->
		
		<!-- JCarousel -->
		<script type="text/javascript" src='{% static "js/jquery.jcarousel.min.js" %}'></script>
		<link rel="stylesheet" media="screen" href='{% static "css/carousel.css" %}' />
		<!-- ENDS JCarousel -->
		
		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>

		<!-- modernizr -->
		<script src='{% static "js/modernizr.js" %}'></script>
		
		<!-- SKIN -->
		<link rel="stylesheet" media="all" href='{% static "css/skin.css" %}'/>
		
		<!-- Less framework -->
		<link rel="stylesheet" media="all" href='{% static "css/lessframework.css" %}'/>
		
		<!-- jplayer -->
		<link href="player-skin/jplayer-black-and-yellow.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src='{% static "js/jquery.jplayer.min.js" %}'></script>
		
		<!-- flexslider -->
		<link rel="stylesheet" href='{% static "css/flexslider.css" %}'>
		<script src='{% static "js/jquery.flexslider.js" %}'></script>
		
	</head>
	
	
	<body>
	
		<!-- HEADER -->
		<header>
			<div class="wrapper cf">

				<div id="logo">
					<a href="{% url 'portfolio:home' %}"><img  src='{% static "img/logo2.png" %}' alt="Simpler"></a>
				</div>
				
				

			</div>
		</header>
		<!-- ENDS HEADER -->


        <!-- MAIN -->
		<div id="main">
			<div class="wrapper cf">






			<!-- portfolio content-->
        	<div id="portfolio-content" class="cf">



				<ul id="filter-buttons">
					<li><a href="#" data-filter="*" class="selected">Show all</a></li>
					<li><a href="#" data-filter=".py">Python</a></li>
					<li><a href="#" data-filter=".cl">C language</a></li>
					<li><a href="#" data-filter=".an">Android</a></li>
                    <li><a href="#" data-filter=".ja">Java</a></li>
					<li><a href="#" data-filter=".js">Java Script</a></li>
				</ul>

				<!-- Filter container -->

				<div id="filter-container" class="cf">


                    <figure class="py">
						<a href="{% url 'portfolio:weather' %}" class="thumb"><img src='{% static "img/dummies/slides/weather.png" %}' alt="alt" /></a>
						<figcaption>
							<a href="{% url 'portfolio:weather' %}" ><h3 class="heading">Weather bot</h3></a>
							<div class="portfolio-cat">
								<a href="#" >Python</a>
							</div>
						</figcaption>
					</figure>


                    <figure class="py js">
						<a href="{% url 'portfolio:sexyDashboard' %}" class="thumb"><img src='{% static "img/dummies/featured/dashboardMain.png" %}' alt="alt" /></a>
						<figcaption>
							<a href="{% url 'portfolio:sexyDashboard' %}" ><h3 class="heading">Sexy Dashboard</h3></a>
							<div class="portfolio-cat">
								<a href="#" >Python&amp;Java Script</a>
							</div>
						</figcaption>
					</figure>



                    <figure class="cl an ja">
						<a href="{% url 'portfolio:cane' %}" class="thumb"><img src='{% static "img/dummies/featured/caneMain.jpg" %}' alt="alt" /></a>
						<figcaption>
							<a href="{% url 'portfolio:cane' %}" ><h3 class="heading">Hurry Cane</h3></a>
							<div class="portfolio-cat">
								<a href="#" >C&amp;Android&amp;Java</a>
							</div>
						</figcaption>
					</figure>


                    <figure class="cl an ja">
						<a href="{% url 'portfolio:cat' %}" class="thumb"><img src='{% static "img/portfolio/catMain.PNG" %}' alt="alt" /></a>
						<figcaption>
							<a href="{% url 'portfolio:cat' %}"><h3 class="heading">Cat Care IoT System</h3></a>
							<div class="portfolio-cat">
								<a href="#" >C&amp;Android&amp;Java</a>
							</div>
						</figcaption>
					</figure>



					<figure class="cl">
						<a href="{% url 'portfolio:maze' %}" class="thumb"><img src='{% static "img/portfolio/maze.png" %}' alt="alt" /></a>
						<figcaption>
							<a href="{% url 'portfolio:maze' %}"><h3 class="heading">Maze Game</h3></a>
							<div class="portfolio-cat">
								<a href="#" >C language</a>
							</div>
						</figcaption>
					</figure>






				</div><!-- ENDS Filter container -->

			</div>
			<!-- ENDS featured -->





			</div><!-- ENDS WRAPPER -->

		</div>
		<!-- ENDS MAIN -->


		<!-- FOOTER -->
		<footer>
			My Portfilio
		</footer>
		<!-- ENDS FOOTER -->
		
	</body>
	
	
	
</html>

jaesay/portfolio/templates/maze.html
{% load staticfiles %}

<!doctype html>
<html class="no-js">

	<head>
		<meta charset="utf-8"/>
		<title>Jaesay Portfolio</title>

		<!--[if lt IE 9]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link rel="stylesheet" media="all" href='{% static "css/style.css" %}'/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->

		<!-- JS -->
		<script src='{% static "js/jquery-1.7.1.min.js" %}'></script>
		<script src='{% static "js/custom.js" %}'></script>
		<script src='{% static "js/tabs.js" %}'></script>
		<script src='{% static "js/css3-mediaqueries.js" %}'></script>
		<script src='{% static "js/jquery.columnizer.min.js" %}'></script>

		<!-- Isotope -->
		<script src='{% static "js/jquery.isotope.min.js" %}'></script>

		<!-- Lof slider -->
		<script src='{% static "js/jquery.easing.js" %}'></script>
		<script src='{% static "js/lof-slider.js" %}'></script>
		<link rel="stylesheet" href='{% static "css/lof-slider.css" %}' media="all"  />
		<!-- ENDS slider -->

		<!-- Tweet -->
		<link rel="stylesheet" href='{% static "css/jquery.tweet.css" %}' media="all"  />
		<script src='{% static "js/tweet/jquery.tweet.js" %}'></script>
		<!-- ENDS Tweet -->

		<!-- superfish -->
		<link rel="stylesheet" media="screen" href='{% static "css/superfish.css" %}' />
		<script  src='{% static "js/superfish-1.4.8/js/hoverIntent.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/superfish.js" %}'></script>
		<script  src='{% static "js/superfish-1.4.8/js/supersubs.js" %}'></script>
		<!-- ENDS superfish -->

		<!-- prettyPhoto -->
		<script  src='{% static "js/prettyPhoto/js/jquery.prettyPhoto.js" %}'></script>
		<link rel="stylesheet" href='{% static "js/prettyPhoto/css/prettyPhoto.css" %}'  media="screen" />
		<!-- ENDS prettyPhoto -->

		<!-- poshytip -->
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-twitter/tip-twitter.css" %}'  />
		<link rel="stylesheet" href='{% static "js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css" %}'  />
		<script  src='{% static "js/poshytip-1.1/src/jquery.poshytip.min.js" %}'></script>
		<!-- ENDS poshytip -->

		<!-- JCarousel -->
		<script type="text/javascript" src='{% static "js/jquery.jcarousel.min.js" %}'></script>
		<link rel="stylesheet" media="screen" href='{% static "css/carousel.css" %}' />
		<!-- ENDS JCarousel -->

		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>

		<!-- modernizr -->
		<script src='{% static "js/modernizr.js" %}'></script>

		<!-- SKIN -->
		<link rel="stylesheet" media="all" href='{% static "css/skin.css" %}'/>

		<!-- Less framework -->
		<link rel="stylesheet" media="all" href='{% static "css/lessframework.css" %}'/>

		<!-- jplayer -->
		<link href="player-skin/jplayer-black-and-yellow.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src='{% static "js/jquery.jplayer.min.js" %}'></script>

		<!-- flexslider -->
		<link rel="stylesheet" href='{% static "css/flexslider.css" %}'>
		<script src='{% static "js/jquery.flexslider.js" %}'></script>
        
                <style type="text/css">
<!--
A:link   { text-decoration: none; }
A:visited   { text-decoration: none; }
A:active   { text-decoration: none; }
A:hover   { text-decoration: none; color: #ff0000; }
//-->
</style>  
		
		
	</head>
	
	
	<body>
	
		<!-- HEADER -->
		<header>
			<div class="wrapper cf">
				
				<div id="logo">
					<a href="{% url 'portfolio:home' %}"><img  src='{% static "img/logo2.png" %}' alt="Simpler"></a>
				</div>

			</div>
		</header>
		<!-- ENDS HEADER -->
		
		<!-- MAIN -->
		<div id="main">
			<div class="wrapper cf">
    	
				
				
				
				<ul id="sub-manu">
					<li><a style="color:#000" class="selected" href="{% url 'portfolio:home' %}">MENU</a></li>
				</ul>
				
			<!-- portfolio content-->
        	<div id="portfolio-content" class="cf">        	
				
				
				
				
				<!-- project pager -->
				<div class="project-pager cf">
					<a class="previous-project" href="{% url 'portfolio:cat' %}">&#8592; Previous project</a>
					<a class="next-project" href="{% url 'portfolio:weather' %}">Next project &#8594;</a>
				</div>
				<!-- ENDS project pager -->
					
					
					<!-- project box -->
				<div class="cheil">
                 <img src='{% static "img/dummies/slides/clearter app/all_4.jpg" %}'>
                 <video style="width:100%;" controls src='{% static "img/dummies/slides/mazeProject.mp4" %}'>
                         Your user agent does not support the HTML5 Video element.
                 </video>
                </div>
	        		
		    	<!-- ENDS project box -->
					
					
				
									
				
    		</div>
    		<!-- ENDS portfolio content-->
			
			
			
			</div><!-- ENDS WRAPPER -->
		</div>
		<!-- ENDS MAIN -->
		
		
		<!-- FOOTER -->
		<footer>
			My Portfilio
		</footer>
		<!-- ENDS FOOTER -->
		
	</body>
	
	
	
</html>